# -----------------------------------------------------------
# Wistia Video Analytics Dashboard (FR11)
# -----------------------------------------------------------
# Author: Rich Kindle
# Description:
#   Interactive Streamlit dashboard displaying Gold-layer metrics
#   from the Wistia Video Analytics pipeline.
# -----------------------------------------------------------

import pandas as pd
import streamlit as st
from utils import safe_numeric, summarize_kpis, trend_indicator
from charts import plays_vs_visitors_chart, engagement_playrate_trend_chart

# -----------------------------------------------------------
# PAGE SETUP
# -----------------------------------------------------------
st.set_page_config(
    page_title="Wistia Video Analytics Dashboard",
    page_icon="🎥",
    layout="wide"
)

st.title("🎬 Wistia Video Analytics Dashboard")
st.markdown(
    """
    This dashboard visualizes aggregated video engagement metrics  
    generated by the AWS-based Wistia Data Pipeline (FR1–FR11).
    """
)

# -----------------------------------------------------------
# LOAD DATA
# -----------------------------------------------------------
@st.cache_data
def load_data():
    df = pd.read_csv("data/sample_gold_data.csv")
    df["load_date"] = pd.to_datetime(df["load_date"], errors="coerce").dt.date
    df = safe_numeric(df, ["total_plays", "total_visitors", "avg_play_rate", "avg_engagement"])
    return df

df = load_data()

# -----------------------------------------------------------
# FILTERS
# -----------------------------------------------------------
st.sidebar.header("Filters")
media_list = df["media_name"].unique().tolist()
selected_media = st.sidebar.multiselect("Select Media:", media_list, default=media_list)

df_filtered = df[df["media_name"].isin(selected_media)]

# -----------------------------------------------------------
# DATE SELECTION
# -----------------------------------------------------------
if "load_date" in df.columns:
    # available_dates = sorted(df["load_date"].unique())
    available_dates = sorted(df["load_date"].astype(str).unique())
else:
    available_dates = []

# Default to the latest load_date
default_date = available_dates[-1] if available_dates else None

selected_date = st.sidebar.selectbox(
    "Select Load Date:",
    options=available_dates,
    index=len(available_dates) - 1 if available_dates else 0,
    help="Choose a specific load_date to explore KPIs for that day."
)

# # -----------------------------------------------------------
# # COMPUTE KPI TRENDS
# # -----------------------------------------------------------

# # Get the latest and previous load_date values
# load_dates = sorted(df_filtered['load_date'].unique())
# if (len(load_dates) >= 2):
#     current_date = load_dates[-1]
#     previous_date = load_dates[-2]
#     df_current = df_filtered[df_filtered['load_date'] == current_date]
#     df_previous = df_filtered[df_filtered['load_date'] == previous_date]
    
#     kpi_current = summarize_kpis(df_current)
#     kpi_previous = summarize_kpis(df_previous)
# else:
#     # Fallback if only one date is available
#     current_date = load_dates[-1] if len(load_dates) > 0 else None
#     kpi_current = summarize_kpis(df_filtered)
#     kpi_previous = kpi_current
# -----------------------------------------------------------
# FILTERED DATA BY SELECTED DATE
# -----------------------------------------------------------
df_selected = df_filtered[df_filtered["load_date"] == selected_date]

# Determine previous date (for comparison)
date_index = available_dates.index(selected_date)
previous_date = available_dates[date_index - 1] if date_index > 0 else None

df_previous = (
    df_filtered[df_filtered["load_date"] == previous_date]
    if previous_date
    else pd.DataFrame(columns=df.columns)
)

kpi_current = summarize_kpis(df_selected)
kpi_previous = summarize_kpis(df_previous) if not df_previous.empty else kpi_current


# -----------------------------------------------------------
# KPI SUMMARY WITH TRENDS
# -----------------------------------------------------------
# st.subheader(f"📊 Key Performance Indicators (as of {current_date})")
st.subheader(f"📊 Key Performance Indicators — {selected_date}")


col1, col2, col3, col4 = st.columns(4)

col1.metric(
    "Total Plays",
    kpi_current["total_plays"],
    trend_indicator(
        float(kpi_current["total_plays"].replace(",", "")),
        float(kpi_previous["total_plays"].replace(",", ""))
    )
)

col2.metric(
    "Total Visitors",
    kpi_current["total_visitors"],
    trend_indicator(
        float(kpi_current["total_visitors"].replace(",", "")),
        float(kpi_previous["total_visitors"].replace(",", ""))
    )
)

col3.metric(
    "Avg Play Rate (%)",
    kpi_current["avg_play_rate"],
    trend_indicator(
        float(kpi_current["avg_play_rate"]),
        float(kpi_previous["avg_play_rate"])
    )
)

col4.metric(
    "Avg Engagement (%)",
    kpi_current["avg_engagement"],
    trend_indicator(
        float(kpi_current["avg_engagement"]),
        float(kpi_previous["avg_engagement"])
    )
)

# -----------------------------------------------------------
# VISUALIZATIONS
# -----------------------------------------------------------
st.divider()
st.subheader("🎞️ Plays vs Visitors by Media")
st.plotly_chart(plays_vs_visitors_chart(df_filtered), use_container_width=True)

st.divider()
st.subheader("📈 Engagement and Play Rate Over Time")
highlight_date = pd.to_datetime(selected_date, errors="coerce")
st.plotly_chart(engagement_playrate_trend_chart(df_filtered, highlight_date), use_container_width=True)


# -----------------------------------------------------------
# FOOTER
# -----------------------------------------------------------
st.divider()
st.markdown(
    """
    **Data Source:** AWS Glue → S3 (Gold Layer)  
    **Author:** Rich Kindle  
    **Stack:** AWS Glue, PySpark, S3, Athena, Streamlit
    """
)
